# Generated by Django 2.0.1 on 2018-03-12 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_import', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemetadata',
            name='date_sent',
            field=models.DateField(null=True),
        ),
    ]
